### ISSUE TITLE
Retrieve and classify projects from the protege-server based on project id

### ISSUE THREAD

**Issue by bdionne** [bdionne/pellet#3]
Currently this is done by listing the project ids in the pellet startup config file. This needs to be done programmatically by contacting the protege server and asking for a list of `classifiable` project ids.

Together with the ability to remotely restart this will enable us to administer the server without sysadmin support.

**Comment by rgrinberg** [comment]
That means the old ability of loading up these project id's from config files is going to be retired right? Or do we want to have the ability get project id's both from protege and the startup file?

**Comment by bdionne** [comment]
just from Protégé, we want to remove the need to modify a config file

**Comment by bdionne** [comment]
This is working well
